// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmeXNlS6dJWR5Qt89SeD_onzpKawnDjQ',
    appId: '1:377422373515:web:d2681d9dc50078c54a6a8e',
    messagingSenderId: '377422373515',
    projectId: 'chatsimple-7442d',
    authDomain: 'chatsimple-7442d.firebaseapp.com',
    storageBucket: 'chatsimple-7442d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4VlI0BocvkkqDuN1pEheQ3gcF_dKno2s',
    appId: '1:377422373515:android:df5a7386828092ff4a6a8e',
    messagingSenderId: '377422373515',
    projectId: 'chatsimple-7442d',
    storageBucket: 'chatsimple-7442d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWEVXTeLvyPjXWts675VJhCKx-yyLCLoc',
    appId: '1:377422373515:ios:a1ae42848d9968e34a6a8e',
    messagingSenderId: '377422373515',
    projectId: 'chatsimple-7442d',
    storageBucket: 'chatsimple-7442d.appspot.com',
    iosBundleId: 'com.example.doan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWEVXTeLvyPjXWts675VJhCKx-yyLCLoc',
    appId: '1:377422373515:ios:fb8be65804e2a1e44a6a8e',
    messagingSenderId: '377422373515',
    projectId: 'chatsimple-7442d',
    storageBucket: 'chatsimple-7442d.appspot.com',
    iosBundleId: 'com.example.doan.RunnerTests',
  );
}
